# Generated by Django 4.1.1 on 2022-10-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_category_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('rating', models.FloatField()),
                ('product_max_price', models.IntegerField()),
                ('product_long_description', models.TextField(blank=True, max_length=500)),
                ('pro_images', models.ImageField(upload_to='photos/products')),
                ('pro_image_1', models.ImageField(upload_to='photos/products')),
                ('pro_image_2', models.ImageField(upload_to='photos/products')),
                ('pro_image_3', models.ImageField(upload_to='photos/products')),
                ('pro_image_4', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Brandinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand_images', models.ImageField(upload_to='photos/brands')),
                ('description', models.TextField(blank=True, max_length=250)),
                ('total_products', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Brandinfo',
                'verbose_name_plural': 'Brandinforms',
            },
        ),
    ]
