# Generated by Django 4.1.1 on 2022-10-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
