# Generated by Django 4.1.1 on 2022-10-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_spec_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spec_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
