# Generated by Django 4.1.1 on 2022-10-08 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_spec_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinfo',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productbrand', to='store.product'),
        ),
    ]
