# Generated by Django 4.1.1 on 2022-10-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_spec_description_and_more'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitems',
            new_name='Cartitem',
        ),
    ]
