# Generated by Django 4.1.1 on 2022-10-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase', to='carts.cart'),
        ),
    ]
