# Generated by Django 4.1.1 on 2022-10-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_available',
        ),
    ]
