# Generated by Django 4.1.1 on 2022-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
