# Generated by Django 4.1.1 on 2022-10-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50),
        ),
    ]
