# Generated by Django 4.1.1 on 2022-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Order cancelled', 'Order cancelled'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
