# Generated by Django 4.1.1 on 2022-10-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
