# Generated by Django 4.1.1 on 2022-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
